language: php
php:
  - 7.4
install:
  - composer install
script:
  - vendor/bin/php-cs-fixer --dry-run -v --allow-risky=yes fix
  - vendor/bin/phpcs
  - vendor/bin/phpstan --memory-limit=256M analyze
  - vendor/bin/phpunit
