name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.4', '8.0']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        id: php-setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: post_max_size=256M, log_errors=1
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      - name: Scan with PHP CS Fixer
        run: PHP_CS_FIXER_IGNORE_ENV=1 composer run-script fixer

      - name: Scan with test PHP Code Sniffer
        run: composer run-script cs

      - name: Run static analysis
        run: composer run-script analyze

      - name: Run test suite
        run: composer run-script coverage

      - name: Estimate coverage
        if: ${{ matrix.php-version == '7.4' }}
        run: composer run-script infection

      - name: SonarCloud Scan
        if: ${{ matrix.php-version == '8.0' }}
        run: ls -l

      - name: SonarCloud Scan
        if: ${{ matrix.php-version == '8.0' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
